// This file is auto-generated. Do not edit manually.

export type Note = 
  | "400ml-water"
  | "DHEA"
  | "HMB"
  | "acetic"
  | "alicin"
  | "ashwagandha"
  | "aspirin"
  | "astaxanthin"
  | "astragalus"
  | "benfotiamine"
  | "berry-tea"
  | "boron"
  | "boswellia"
  | "brazil nut"
  | "brazil-nut"
  | "bromelain"
  | "bumbkin-seed"
  | "cacao"
  | "cardio"
  | "casein"
  | "cashew"
  | "chia"
  | "cinamon"
  | "cistanche"
  | "coffee"
  | "cold"
  | "couch"
  | "creatine"
  | "curcumin"
  | "digest-enzyme"
  | "egg"
  | "ems"
  | "fenugreek"
  | "fish-oil"
  | "fucoidan"
  | "gac oil"
  | "gac-oil"
  | "ginger"
  | "gingseng"
  | "ginkgo"
  | "glycine"
  | "green-tea"
  | "gymnema-sylvestre"
  | "incarin"
  | "kava"
  | "lactoferrin"
  | "lecithin"
  | "lipoic-acid"
  | "magiesum-glycinate"
  | "magnesium-glycinate"
  | "magnesium-malate"
  | "marrow"
  | "melatonin"
  | "melatonin low"
  | "milk-thistle"
  | "mulberry-leaf-tea"
  | "nac"
  | "niacin"
  | "nutritionyeast"
  | "olive oil"
  | "oyster"
  | "pregnenolone"
  | "pumbkin seed"
  | "red-light"
  | "sleep-aid"
  | "solanum-trilobatum"
  | "sun-light"
  | "taurine"
  | "testo-binaural"
  | "theanine"
  | "thotitu"
  | "tmg"
  | "vibration"
  | "vitamin-c"
  | "vitamin-d"
  | "walk"
  | "yeast"
  | "yohourt";

export type UpdateNote = `${string}${Note}`;
